### ISSUE TITLE
安装以后如何删除

### ISSUE THREAD

**Issue by aalj** [FunctionClub/V2ray.Fun#14]

**Comment by mochaaP** [comment]
感觉像个半成品

**Comment by iii80** [comment]
v2ray
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 30, in <module>
    data = json.loads(data_file.read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 3 column 24 (char 45)

**Comment by Punizione** [comment]
@iii80 可能是安装没成功 麻烦额外开个Issues讨论
