### ISSUE TITLE
与3322.org链接不畅的环境下脚本无法正常运行

### ISSUE THREAD

**Issue by aqaqaqq** [FunctionClub/v2ray.fun#16]
由于使用了3322.org的获取IP的API `http://members.3322.org/dyndns/getip`，在服务器无法访问3322.org时，脚本在执行大部分操作（如重启服务、更改配置）时会卡住，强行终止脚本报错如下：
```
^CTraceback (most recent call last):
  File "/usr/local/v2ray.fun/serverinfo.py", line 8, in <module>
    myip = urllib2.urlopen('http://members.3322.org/dyndns/getip').read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 562, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```
希望增加墙外的IP API.

**Comment by YLWS-4617** [comment]
已经修复，期待修复后反馈结果~

**Comment by aqaqaqq** [comment]
经测试，脚本能顺利运行，感谢~
