### ISSUE TITLE
20171021 运行upgrade.sh后出现的错误

### ISSUE THREAD

**Issue by LennoC** [FunctionClub/v2ray.fun#17]
运行upgrade.sh更新后重启服务提示错误如下：
Traceback (most recent call last):
  File "/usr/local/v2ray.fun/serverinfo.py", line 8, in <module>
    myip = urllib2.urlopen('https://api.ipify.org').read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

在这之前几天有运行过一次升级，结果SSL失效了。今天重启v2ray时就遇到这个报错。看名字应该是证书出错了，但我不懂。。。

**Comment by YLWS-4617** [comment]
嗯，了解了，是Python 的库的问题，无法验证HTTPS网站的证书。我改天找个时间修复下。
