### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by lukemin** [FunctionClub/V2ray.Fun#48]
- 问题类型 : 
  - [ ] bug反馈
  - [ ] 新功能建议
  - [ ] 其它
  
----
问题详情
----

- 操作系统: 
- 内核版本: 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

- Python版本: 
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
- Bash版本: 
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
- 脚本版本 (或者commit号): 
 
**问题描述**

 
**如何复现**

 
错误信息：
Cloning into 'V2ray.Fun'...
remote: Enumerating objects: 491, done.
remote: Total 491 (delta 0), reused 0 (delta 0), pack-reused 491
Receiving objects: 100% (491/491), 2.60 MiB | 1.37 MiB/s, done.
Resolving deltas: 100% (251/251), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "init.py", line 4, in <module>
    import Config_Generator
  File "/usr/local/V2ray.Fun/Config_Generator.py", line 4, in <module>
    import urllib2
ImportError: No module named 'urllib2'
mkdir: cannot create directory ‘/etc/supervisor’: File exists
mkdir: cannot create directory ‘/etc/supervisor/conf.d’: File exists
Traceback (most recent call last):
  File "/usr/bin/echo_supervisord_conf", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'supervisor==3.2.0' distribution was not found and is required by the application
请输入默认用户名[默认admin]： 
请输入默认登录密码[默认admin]： 
请输入监听端口号[默认5000]： 
chmod: cannot access '/etc/v2ray/config.json': No such file or directory
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'supervisor==3.2.0' distribution was not found and is required by the application
安装成功！

面板端口：5000
默认用户名：admin
默认密码：admin

输入 v2ray 并回车可以手动管理网页面板相关功能
You have new mail in /var/mail/root
root@instance-2:/# ^C
root@instance-2:/# v2ray
Traceback (most recent call last):
  File "/usr/local/bin/v2ray", line 5, in <module>
    import commands
ImportError: No module named 'commands'
root@instance-2:/#

**Comment by fifteenzhang** [comment]
手动安装supervisor，并且创建对应配置/etc/supervisor/supervisord.conf，记得command里面是v2ray安装的地址


[include] 
files = /etc/supervisor/conf.d/*.ini 

[supervisord] 

[inet_http_server] 
port=127.0.0.1:9081 

[rpcinterface:supervisor] 
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface 

[supervisorctl] 
serverurl=http://127.0.0.1:9001 

[program:v2ray] 
command=/usr/local/bin/v2ray -config /path/to/v2ray-client.conf 
autostart=true 
process_name=%(program_name)s 
redirect_stderr=true 
stdout_logfile=/usr/local/log/v2ray.log 
stdout_logfile_maxbytes=1MB 
stdout_logfile_back=0

**Comment by lukemin** [comment]
应该是你的程序是python2写的，我默认python3造成的，在环境变量上修正一下就好了
