### ISSUE TITLE
Ubuntu 18.04  v2ray.fun: ERROR (spawn error)

### ISSUE THREAD

**Issue by JimmyTeng** [FunctionClub/V2ray.Fun#59]
Ubuntu 18.04
下面遇到
请选择：1
v2ray.fun: ERROR (spawn error)
启动成功!

的问题 ？ 求原因？

**Comment by wenchengxucool** [comment]
Debian 10 同样出错。

作者使用supervisorctl start v2ray.fun启动一个进程。

使用supervisorctl tail v2ray.fun stdout发现：

Traceback (most recent call last):
  File "/usr/local/V2ray.Fun/app.py", line 8, in <module>
    from config_generator import *  # noqa
ImportError: No module named config_generator

发现其实作者写的文件是Config_Generator.py，是大写的C和G。所以只需要改一下from config_generator import * 那一行的大小写就行了。或者把文件名改改就行了。我选择了改文件名

之后又报一个错误：
Traceback (most recent call last):
  File "/usr/local/V2ray.Fun/app.py", line 261, in <module>
    data = json.loads(f)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

定位到作者源码的这段：
with open("v2ray.config") as f:
    data = json.loads(f)

看了一眼v2ray.config这个文件，f不能那么读取。

需要加一行改成：
with open("v2ray.config") as f:
    data = f.read()
    data = json.loads(data)

改完以上发现可以启动面板了。。但是就是翻不了墙。

至少有下面一个问题：
1.获取本机ip方式
def getip():
    myip = urllib2.urlopen('https://cn.fdos.me/ip.php').read()
    myip = myip.strip()
    return str(myip)
至少在我但机器上报这个错误：
  File "Config_Generator.py", line 9, in getip
    myip = urllib2.urlopen('https://cn.fdos.me/ip.php').read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
这个网址已经失效了，改成了https://ident.me

之后我就完全跑起来了。跑起来以后，发现“传输方式”选择KCP根本不能用，于是就选了TCP。

最后我终于弄通了。本来发个PR，但觉得太麻烦了。还是写在issue里记录下来，让其他人看见自己改算了。也不麻烦。。

**Comment by Leezj9671** [comment]
我看了一下 `supervisorctl tail v2ray.fun stdout`，发现是提示
```
Traceback (most recent call last):
  File "/usr/local/V2ray.Fun/app.py", line 8, in <module>
    from config_generator import *  # noqa
ImportError: No module named config_generator
```

怕影响到其它，直接复制了文件就可以了
```
cp Config_Generator.py config_generator.py
```

**Comment by wenchengxucool** [comment]
> 我看了一下 `supervisorctl tail v2ray.fun stdout`，发现是提示
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/V2ray.Fun/app.py", line 8, in <module>
>     from config_generator import *  # noqa
> ImportError: No module named config_generator
> ```
> 
> 怕影响到其它，直接复制了文件就可以了
> 
> ```
> cp Config_Generator.py config_generator.py
> ```

😁只有init和app两个文件会依赖config_generator.py。并没有其他依赖的地方。我已经愉快地跑起来了。。

**Comment by CMo11001100** [comment]
> Debian 10同样出错。
> 
> 作者使用supervisorctl start v2ray.fun启动一个进程。
> 
> 使用supervisorctl tail v2ray.fun stdout发现：
> 
> 回溯（最近一次调用最后一次）：
> 文件“/usr/local/V2ray.Fun/app.py”，第8行，
> 来自config_generator import * #noqa 
> ImportError：没有名为config_generator的模块
> 
> 发现其实作者写的文件是Config_Generator.py，是大写的C和G.所以只需要改一下从config_generator import *那一行的大小写就行了。或者把文件名改改就行了。我选择了改文件名
> 
> 之后又报一个错误：
> Traceback（最近一次调用最后一次）：
> 文件“/usr/local/V2ray.Fun/app.py”，第261行，在
> data = json.loads（f）
> 文件“/ usr / lib / python2 .7 / json / **init** .py“，第339行，在load中
> 返回_default_decoder.decode（s）
> 文件”/usr/lib/python2.7/json/decoder.py“，第364行，在解码
> obj中，end = self .raw_decode（s，idx = _w（s，0）.end（））
> TypeError：期望的字符串或缓冲区
> 
> 定位到作者源码的这段：
> 用open（“v2ray.config”）作为f：
> data = json.loads（f）
> 
> 看了一眼v2ray.config这个文件，F不能那么读取。
> 
> 需要加一行改成：
> 用open（“v2ray.config”）作为f：
> data = f.read（）
> data = json.loads（data）
> 
> 改完以上发现可以启动面板了..但是就是翻不了墙。
> 
> 至少有下面一个问题：
> 1。获取本机ip方式
> def getip（）：
> myip = [urllib2.urlopen（](https://cn.fdos.me/ip.php').read() ' [https://cn.fdos.me/ip.php'）。read（](https://cn.fdos.me/ip.php').read()）
> myip = myip.strip（ ）
> return str（myip）
> 至少在我但机器上报这个错误：
> 文件“1.p​​y”，第3行，在getip 
> myip = urllib2.urlopen （' [https://cn.fdos.me/ip.php'）中。 read（](https://cn.fdos.me/ip.php').read()）
> 文件“/usr/lib/python2.7/urllib2.py”，第154行，在urlopen中
> 返回opener.open（url，data，timeout）
> 文件“/usr/lib/python2.7/urllib2.py” ，第429行，在open 
> 响应中= self._open（req，data）
> 文件“/usr/lib/python2.7/urllib2.py”，第447行，在
> _open'_open'中，req）
> 文件“/ usr / lib / python2.7 / urllib2.py“，第407行，in _call_chain 
> result = func（* args）
> 文件“/usr/lib/python2.7/urllib2.py”，第1241行，在https_open 
> context = self._context）
> 文件“/usr/lib/python2.7/urllib2.py”，第1198行，在do_open中
> 提升URLError （错误）
> urllib2.URLError：<urlopen错误[Errno 111]拒绝连接> 
> 这个网址已经失效了，改成了https://ident.me
> 
> 之后我就完全跑起来了跑。起来以后，发现“传输方式”选择KCP根本不能用，于是就选了TCP。
> 
> 最后我终于弄通了。本来发个PR，但觉得太麻烦了。还是写在问题里记录下来，让其他人看见自己改算了。也不麻烦..

按着大佬的方法改了一遍之后还是不能启动，依然报v2ray.fun: ERROR (spawn error)

> 文件“1.p​​y”，第3行，在getip 

也并没有找到这个文件
希望大佬能再讲解一下23333

**Comment by wenchengxucool** [comment]
> > Debian 10同样出错。
> > 作者使用supervisorctl start v2ray.fun启动一个进程。
> > 使用supervisorctl tail v2ray.fun stdout发现：
> > 回溯（最近一次调用最后一次）：
> > 文件“/usr/local/V2ray.Fun/app.py”，第8行，
> > 来自config_generator import * #noqa
> > ImportError：没有名为config_generator的模块
> > 发现其实作者写的文件是Config_Generator.py，是大写的C和G.所以只需要改一下从config_generator import *那一行的大小写就行了。或者把文件名改改就行了。我选择了改文件名
> > 之后又报一个错误：
> > Traceback（最近一次调用最后一次）：
> > 文件“/usr/local/V2ray.Fun/app.py”，第261行，在
> > data = json.loads（f）
> > 文件“/ usr / lib / python2 .7 / json / **init** .py“，第339行，在load中
> > 返回_default_decoder.decode（s）
> > 文件”/usr/lib/python2.7/json/decoder.py“，第364行，在解码
> > obj中，end = self .raw_decode（s，idx = _w（s，0）.end（））
> > TypeError：期望的字符串或缓冲区
> > 定位到作者源码的这段：
> > 用open（“v2ray.config”）作为f：
> > data = json.loads（f）
> > 看了一眼v2ray.config这个文件，F不能那么读取。
> > 需要加一行改成：
> > 用open（“v2ray.config”）作为f：
> > data = f.read（）
> > data = json.loads（data）
> > 改完以上发现可以启动面板了..但是就是翻不了墙。
> > 至少有下面一个问题：
> > 1。获取本机ip方式
> > def getip（）：
> > myip = [urllib2.urlopen（](https://cn.fdos.me/ip.php').read() ' [https://cn.fdos.me/ip.php'）。read（](https://cn.fdos.me/ip.php').read()）
> > myip = myip.strip（ ）
> > return str（myip）
> > 至少在我但机器上报这个错误：
> > 文件“1.p​​y”，第3行，在getip
> > myip = urllib2.urlopen （' [https://cn.fdos.me/ip.php'）中。 read（](https://cn.fdos.me/ip.php').read()）
> > 文件“/usr/lib/python2.7/urllib2.py”，第154行，在urlopen中
> > 返回opener.open（url，data，timeout）
> > 文件“/usr/lib/python2.7/urllib2.py” ，第429行，在open
> > 响应中= self._open（req，data）
> > 文件“/usr/lib/python2.7/urllib2.py”，第447行，在
> > _open'_open'中，req）
> > 文件“/ usr / lib / python2.7 / urllib2.py“，第407行，in _call_chain
> > result = func（* args）
> > 文件“/usr/lib/python2.7/urllib2.py”，第1241行，在https_open
> > context = self._context）
> > 文件“/usr/lib/python2.7/urllib2.py”，第1198行，在do_open中
> > 提升URLError （错误）
> > urllib2.URLError：<urlopen错误[Errno 111]拒绝连接>
> > 这个网址已经失效了，改成了https://ident.me
> > 之后我就完全跑起来了跑。起来以后，发现“传输方式”选择KCP根本不能用，于是就选了TCP。
> > 最后我终于弄通了。本来发个PR，但觉得太麻烦了。还是写在问题里记录下来，让其他人看见自己改算了。也不麻烦..
> 
> 按着大佬的方法改了一遍之后还是不能启动，依然报v2ray.fun: ERROR (spawn error)
> 
> > 文件“1.p​​y”，第3行，在getip
> 
> 也并没有找到这个文件
> 希望大佬能再讲解一下23333

应该是File "Config_Generator.py", line 9, in getip：这一行。我把作者源文件里代码粘贴出来新建了一个1.py，测试报错。结果我把新建的文件报错给粘过来了。已修改～

**Comment by bzd111** [comment]
可以使用新的版本再试下，上面的问题都已修复了

**Comment by arctg70** [comment]
新版本还是一样出错
Traceback (most recent call last):
  File "/usr/local/V2ray.Fun/app.py", line 262, in <module>
    data = json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by arctg70** [comment]
> 新版本还是一样出错
> Traceback (most recent call last):
> File "/usr/local/V2ray.Fun/app.py", line 262, in
> data = json.loads(data)
> File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
> raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
可以了，原来真的v2ray.config没有json object，安装的时候这个文件不知为何是空的。重新拷贝了一份进去就好了。

**Comment by zyh001** [comment]
> Debian 10 同样出错。
> 
> 作者使用supervisorctl start v2ray.fun启动一个进程。
> 
> 使用supervisorctl tail v2ray.fun stdout发现：
> 
> Traceback (most recent call last):
> File "/usr/local/V2ray.Fun/app.py", line 8, in
> from config_generator import * # noqa
> ImportError: No module named config_generator
> 
> 发现其实作者写的文件是Config_Generator.py，是大写的C和G。所以只需要改一下from config_generator import * 那一行的大小写就行了。或者把文件名改改就行了。我选择了改文件名
> 
> 之后又报一个错误：
> Traceback (most recent call last):
> File "/usr/local/V2ray.Fun/app.py", line 261, in
> data = json.loads(f)
> File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> TypeError: expected string or buffer
> 
> 定位到作者源码的这段：
> with open("v2ray.config") as f:
> data = json.loads(f)
> 
> 看了一眼v2ray.config这个文件，f不能那么读取。
> 
> 需要加一行改成：
> with open("v2ray.config") as f:
> data = f.read()
> data = json.loads(data)
> 
> 改完以上发现可以启动面板了。。但是就是翻不了墙。
> 
> 至少有下面一个问题：
> 1.获取本机ip方式
> def getip():
> myip = urllib2.urlopen('https://cn.fdos.me/ip.php').read()
> myip = myip.strip()
> return str(myip)
> 至少在我但机器上报这个错误：
> File "Config_Generator.py", line 9, in getip
> myip = urllib2.urlopen('https://cn.fdos.me/ip.php').read()
> File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
> return opener.open(url, data, timeout)
> File "/usr/lib/python2.7/urllib2.py", line 429, in open
> response = self._open(req, data)
> File "/usr/lib/python2.7/urllib2.py", line 447, in _open
> '_open', req)
> File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
> result = func(*args)
> File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
> context=self._context)
> File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
> raise URLError(err)
> urllib2.URLError: <urlopen error [Errno 111] Connection refused>
> 这个网址已经失效了，改成了https://ident.me
> 
> 之后我就完全跑起来了。跑起来以后，发现“传输方式”选择KCP根本不能用，于是就选了TCP。
> 
> 最后我终于弄通了。本来发个PR，但觉得太麻烦了。还是写在issue里记录下来，让其他人看见自己改算了。也不麻烦。。

您好，建议您提交PR，该程序目前已经处于不再维护的状态
